channel_sources:
  - realthunder,conda-forge
channel_targets:
  - realthunder main
MACOSX_SDK_VERSION:
  - '11.0'
qt_main:
  - '5.15.8'
c_compiler:         # [win]
  - clang           # [win]
cxx_compiler:       # [win]
  - clangxx         # [win]
qt:
  - "5"
