{% set name = "pivy-rt" %}
{% set version = "0.6.10" %}

{% if qt is undefined %}
{% set qt = "6" %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: pivy.tar.gz
  url: https://github.com/coin3d/pivy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7b409816c9fad84cf94f93659281f9dd2501d285eb2fc609e9401a3d004ce723
  patches:
    - patches/windows_cmake_install_path_fix.patch
    - patches/extend_install_rpath.patch

build:
  number: 4
  string: py{{ CONDA_PY }}qt{{ qt }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script_env:
  {% if qt|int >=6 %}
    - USE_QT6=1
  {% else %}
    - USE_QT6=0
  skip: true  # [py>311]
  {% endif %}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - msinttypes                             # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d-rt
  {% if qt|int >=6 %}
    - qt6-main
    - soqt6-rt
  {% else %}
    - qt-main
    - soqt-rt
  {% endif %}
  run:
    - python

# test:
#   imports:
#     - pivy.coin
#     - pivy.gui.soqt

about:
  home: https://github.com/realthunder/coin
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d with enhanced shadow rendering.

extra:
  recipe-maintainers:
    - realthunder
